# Tests the Graylog integration

import pytest

from lib.class_helper import Alert, CaseFile, Rule, ContextProcess, ContextLog, ContextFlow
from integrations.graylog import (
    irsoar_provide_new_alerts,
    acknowledge_alert,
    create_alert_from_doc
)
import lib.logging_helper as logging_helper
import lib.config_helper as config_helper
import datetime
import uuid

TEST_RESULTS = {
    "took":  7,
    "timed_out":  "false",
    "_shards":  {
                    "total":  4,
                    "successful":  4,
                    "skipped":  0,
                    "failed":  0
                },
    "hits":  {
                 "total":  {
                               "value":  10000,
                               "relation":  "gte"
                           },
                 "max_score":  1.0,
                 "hits":  [
                              {
                                  "_index":  "wazuh_alert_1_perfix_0",
                                  "_id":  "06e28630-c14f-11ee-b713-000c292285df",
                                  "_score":  1.0,
                                  "_source":  {
                                                  "source_reserved_ip":  "true",
                                                  "data_win_system_eventRecordID":  "5790",
                                                  "agent_id":  "003",
                                                  "agent_name":  "DESKTOP-UBNTINP",
                                                  "data_win_eventdata_sourceProcessGUID":  "{6f026a73-a6d7-65ba-7100-000000000500}",
                                                  "gl2_remote_ip":  "192.168.59.130",
                                                  "data_win_system_eventID":  "10",
                                                  "gl2_remote_port":  39692,
                                                  "source":  "192.168.59.130",
                                                  "data_win_eventdata_targetImage":  "C:\\\\Users\\\\Administrator\\\\AppData\\\\Local\\\\Microsoft\\\\OneDrive\\\\OneDrive.exe",
                                                  "gl2_source_input":  "65b67daf8ee8cf109aa47ccd",
                                                  "rule_level":  3,
                                                  "data_win_eventdata_sourceUser":  "WINDOWSCOMPANON\\\\Administrator",
                                                  "data_win_system_task":  "10",
                                                  "data_win_system_threadID":  "5780",
                                                  "rule_description":  "Sysmon - Event 10: ProcessAccess by C:\\\\Windows\\\\Explorer.EXE",
                                                  "gl2_source_node":  "90642c69-49a0-4566-8fcc-92a46421e216",
                                                  "id":  "1706825560.5465648",
                                                  "data_win_eventdata_grantedAccess":  "0x1410",
                                                  "data_win_eventdata_sourceImage":  "C:\\\\Windows\\\\Explorer.EXE",
                                                  "rule_mitre_tactic":  "Defense Evasion, Privilege Escalation",
                                                  "gl2_accounted_message_size":  8087,
                                                  "data_win_eventdata_utcTime":  "2024-02-01 22:12:36.898",
                                                  "streams":  [
                                                                  "65b800c7ef47be2bbc6927a3"
                                                              ],
                                                  "rule_mitre_id":  "T1055",
                                                  "gl2_message_id":  "01HNKBPHGQ7REF6WTHZWNMFYV5",
                                                  "data_win_system_computer":  "windowscompanone",
                                                  "agent_ip_reserved_ip":  "true",
                                                  "data_win_eventdata_ruleName":  "technique_id=T1055.001,technique_name=Dynamic-link Library Injection",
                                                  "agent_ip":  "192.168.59.132",
                                                  "rule_groups2":  "sysmon",
                                                  "rule_groups1":  "windows",
                                                  "rule_groups3":  "sysmon_event_10",
                                                  "true":  1706825560.992214,
                                                  "rule_groups":  "windows, sysmon, sysmon_event_10",
                                                  "data_win_system_keywords":  "0x8000000000000000",
                                                  "data_win_system_level":  "4",
                                                  "data_win_eventdata_targetProcessGUID":  "{6f026a73-ba80-65bb-8705-000000000500}",
                                                  "data_win_system_severityValue":  "INFORMATION",
                                                  "data_win_eventdata_targetUser":  "WINDOWSCOMPANON\\\\Administrator",
                                                  "rule_mitre_technique":  "Process Injection",
                                                  "rule_firedtimes":  1,
                                                  "data_win_system_systemTime":  "2024-02-01T22:12:36.9636668Z",
                                                  "rule_mail":  "false",
                                                  "log_type":  "wazuh_1",
                                                  "decoder_name":  "windows_eventchannel",
                                                  "data_win_system_processID":  "456",
                                                  "data_win_system_channel":  "Microsoft-Windows-Sysmon/Operational",
                                                  "data_win_system_providerName":  "Microsoft-Windows-Sysmon",
                                                  "data_win_system_version":  "3",
                                                  "data_win_system_providerGuid":  "{5770385f-c22a-43e0-bf4c-06f5698ffbd9}",
                                                  "timestamp":  "2024-02-01 22:12:45.719",
                                                  "data_win_eventdata_callTrace":  "C:\\\\Windows\\\\SYSTEM32\\\\ntdll.dll+9d4a4|C:\\\\Windows\\\\System32\\\\KERNELBASE.dll+308ee|C:\\\\Windows\\\\System32\\\\appresolver.dll+24c11|C:\\\\Windows\\\\System32\\\\appresolver.dll+21bd7|C:\\\\Windows\\\\System32\\\\appresolver.dll+21916|C:\\\\Windows\\\\Explorer.EXE+6c285|C:\\\\Windows\\\\Explorer.EXE+52b6f|C:\\\\Windows\\\\Explorer.EXE+4e397|C:\\\\Windows\\\\Explorer.EXE+4daef|C:\\\\Windows\\\\Explorer.EXE+46a6f|C:\\\\Windows\\\\Explorer.EXE+45d54|C:\\\\Windows\\\\Explorer.EXE+6f507|C:\\\\Windows\\\\Explorer.EXE+7a0c8|C:\\\\Windows\\\\System32\\\\user32.dll+e858|C:\\\\Windows\\\\System32\\\\user32.dll+e3dc|C:\\\\Windows\\\\System32\\\\user32.dll+22830|C:\\\\Windows\\\\SYSTEM32\\\\ntdll.dll+a0e64|UNKNOWN(FFFFF8033A070FF5)|UNKNOWN(FFFFE4CCBE2E86CB)|UNKNOWN(FFFFE4CCBE316E04)|UNKNOWN(FFFFE4CCBE315E64)|UNKNOWN(FFFFE4CCBE3138A8)|UNKNOWN(FFFFE4CCBE312AE8)|UNKNOWN(FFFFE4CCBE7371AE)",
                                                  "data_win_system_opcode":  "0",
                                                  "gl2_processing_error":  "Replaced invalid timestamp value in message \u003c06e28630-c14f-11ee-b713-000c292285df\u003e with current time - Value \u003c2024-02-01T17:12:40.091-0500\u003e caused exception: Invalid format: \"2024-02-01T17:12:40.091-0500\" is malformed at \"T17:12:40.091-0500\".",
                                                  "data_win_eventdata_sourceProcessId":  "3808",
                                                  
                                                  "rule_id":  "109102",
                                                  "manager_name":  "wazuhmanager",
                                                  "location":  "EventChannel",
                                                  "data_win_eventdata_targetProcessId":  "6404",
                                                  "data_win_system_message":  "\"Process accessed:\r\nRuleName: technique_id=T1055.001,technique_name=Dynamic-link Library Injection\r\nUtcTime: 2024-02-01 22:12:36.898\r\nSourceProcessGUID: {6f026a73-a6d7-65ba-7100-000000000500}\r\nSourceProcessId: 3808\r\nSourceThreadId: 2848\r\nSourceImage: C:\\Windows\\Explorer.EXE\r\nTargetProcessGUID: {6f026a73-ba80-65bb-8705-000000000500}\r\nTargetProcessId: 6404\r\nTargetImage: C:\\Users\\Administrator\\AppData\\Local\\Microsoft\\OneDrive\\OneDrive.exe\r\nGrantedAccess: 0x1410\r\nCallTrace: C:\\Windows\\SYSTEM32\\ntdll.dll+9d4a4|C:\\Windows\\System32\\KERNELBASE.dll+308ee|C:\\Windows\\System32\\appresolver.dll+24c11|C:\\Windows\\System32\\appresolver.dll+21bd7|C:\\Windows\\System32\\appresolver.dll+21916|C:\\Windows\\Explorer.EXE+6c285|C:\\Windows\\Explorer.EXE+52b6f|C:\\Windows\\Explorer.EXE+4e397|C:\\Windows\\Explorer.EXE+4daef|C:\\Windows\\Explorer.EXE+46a6f|C:\\Windows\\Explorer.EXE+45d54|C:\\Windows\\Explorer.EXE+6f507|C:\\Windows\\Explorer.EXE+7a0c8|C:\\Windows\\System32\\user32.dll+e858|C:\\Windows\\System32\\user32.dll+e3dc|C:\\Windows\\System32\\user32.dll+22830|C:\\Windows\\SYSTEM32\\ntdll.dll+a0e64|UNKNOWN(FFFFF8033A070FF5)|UNKNOWN(FFFFE4CCBE2E86CB)|UNKNOWN(FFFFE4CCBE316E04)|UNKNOWN(FFFFE4CCBE315E64)|UNKNOWN(FFFFE4CCBE3138A8)|UNKNOWN(FFFFE4CCBE312AE8)|UNKNOWN(FFFFE4CCBE7371AE)\r\nSourceUser: WINDOWSCOMPANON\\Administrator\r\nTargetUser: WINDOWSCOMPANON\\Administrator\"",
                                                  "data_win_eventdata_sourceThreadId":  "2848"
                                              }
                              },
                              {
                                  "_index":  "wazuh_alert_1_perfix_0",
                                  "_id":  "21b548d0-c14f-11ee-b713-000c292285df",
                                  "_score":  1.0,
                                  "_source":  {
                                                  "source_reserved_ip":  "true",
                                                  "agent_id":  "002",
                                                  "agent_name":  "DESKTOP-GJA3NM0",
                                                  "decoder_parent":  "ossec",
                                                  "gl2_remote_ip":  "192.168.59.130",
                                                  "gl2_remote_port":  44152,
                                                  "rule_tsc":  "CC7.2, CC7.3, CC6.8",
                                                  "rule_gdpr":  "IV_35.7.d",
                                                  "source":  "192.168.59.130",
                                                  "gl2_source_input":  "65b67daf8ee8cf109aa47ccd",
                                                  "rule_level":  3,
                                                  "rule_firedtimes":  1,
                                                  "full_log":  "ossec: Agent started: \u0027DESKTOP-GJA3NM0-\u003eany\u0027.",
                                                  "rule_mail":  "false",
                                                  "rule_pci_dss":  "10.6.1, 10.2.6",
                                                  "log_type":  "wazuh_1",
                                                  "rule_nist_800_53":  "AU.6, AU.14, AU.5",
                                                  "decoder_name":  "ossec",
                                                  "rule_description":  "Ossec agent started.",
                                                  "gl2_source_node":  "90642c69-49a0-4566-8fcc-92a46421e216",
                                                  "id":  "1706825608.5472643",
                                                  "timestamp":  "2024-02-01 22:13:30.724",
                                                  "gl2_accounted_message_size":  1316,
                                                  "gl2_processing_error":  "Replaced invalid timestamp value in message \u003c21b548d0-c14f-11ee-b713-000c292285df\u003e with current time - Value \u003c2024-02-01T17:13:28.520-0500\u003e caused exception: Invalid format: \"2024-02-01T17:13:28.520-0500\" is malformed at \"T17:13:28.520-0500\".",
                                                  "streams":  [
                                                                  "65b800c7ef47be2bbc6927a3"
                                                              ],
                                                  "gl2_message_id":  "01HNKBQXF4DC73R3YHNN6VZQJV",
                                                  
                                                  "agent_ip_reserved_ip":  "true",
                                                  "rule_id":  "503",
                                                  "agent_ip":  "192.168.59.131",
                                                  "manager_name":  "wazuhmanager",
                                                  "rule_groups1":  "ossec",
                                                  "rule_gpg13":  "10.1",
                                                  "true":  1706825609.017451,
                                                  "data_extra_data":  "DESKTOP-GJA3NM0-\u003eany",
                                                  "rule_hipaa":  "164.312.b",
                                                  "location":  "wazuh-agent",
                                                  "rule_groups":  "ossec"
                                              }
                              },
                              {
                                  "_index":  "wazuh_alert_1_perfix_0",
                                  "_id":  "24b01240-c14f-11ee-b713-000c292285df",
                                  "_score":  1.0,
                                  "_source":  {
                                                  "data_win_eventdata_description":  "Host Process for Windows Tasks",
                                                  "source_reserved_ip":  "true",
                                                  "data_win_system_eventRecordID":  "2010230",
                                                  "data_win_eventdata_user":  "NT AUTHORITY\\\\SYSTEM",
                                                  "agent_id":  "002",
                                                  "agent_name":  "DESKTOP-GJA3NM0",
                                                  "gl2_remote_ip":  "192.168.59.130",
                                                  "data_win_system_eventID":  "1",
                                                  "gl2_remote_port":  59614,
                                                  "source":  "192.168.59.130",
                                                  "gl2_source_input":  "65b67daf8ee8cf109aa47ccd",
                                                  "rule_level":  3,
                                                  "data_win_eventdata_originalFileName":  "taskhostw.exe",
                                                  "data_win_eventdata_company":  "Microsoft Corporation",
                                                  "data_win_system_task":  "1",
                                                  "data_win_system_threadID":  "5564",
                                                  "rule_description":  "Sysmon - Event 1: Process creation Host Process for Windows Tasks",
                                                  "data_win_eventdata_parentUser":  "NT AUTHORITY\\\\SYSTEM",
                                                  "gl2_source_node":  "90642c69-49a0-4566-8fcc-92a46421e216",
                                                  "id":  "1706825612.5516626",
                                                  "rule_mitre_tactic":  "Privilege Escalation, Persistence",
                                                  "gl2_accounted_message_size":  6500,
                                                  "data_win_eventdata_integrityLevel":  "System",
                                                  "data_win_eventdata_utcTime":  "2024-02-01 22:13:05.384",
                                                  "streams":  [
                                                                  "65b800c7ef47be2bbc6927a3"
                                                              ],
                                                  "rule_mitre_id":  "T1546",
                                                  "gl2_message_id":  "01HNKBR2B6Y1TR61684EMN8ZNF",
                                                  "data_win_system_computer":  "DESKTOP-GJA3NM0",
                                                  "data_win_eventdata_currentDirectory":  "C:\\\\Windows\\\\system32\\\\",
                                                  "agent_ip_reserved_ip":  "true",
                                                  "data_win_eventdata_hashes":  "SHA256=976BB3FB062818E9643EC7F65BE2F267B90F63BD9F8BE0E6212D131183136140",
                                                  "agent_ip":  "192.168.59.131",
                                                  "data_win_eventdata_image":  "C:\\\\Windows\\\\System32\\\\taskhostw.exe",
                                                  "rule_groups2":  "sysmon",
                                                  "rule_groups1":  "windows",
                                                  "rule_groups3":  "sysmon_event1",
                                                  "data_win_eventdata_parentProcessGuid":  "{23c79bc1-176f-65bc-1a00-000000001200}",
                                                  "true":  1706825612.88061,
                                                  "data_win_eventdata_parentProcessId":  "1220",
                                                  "rule_groups":  "windows, sysmon, sysmon_event1, windows_sysmon_event1",
                                                  "data_win_system_keywords":  "0x8000000000000000",
                                                  "data_win_system_level":  "4",
                                                  "data_win_eventdata_fileVersion":  "10.0.19041.3636 (WinBuild.160101.0800)",
                                                  "data_win_eventdata_parentImage":  "C:\\\\Windows\\\\System32\\\\svchost.exe",
                                                  "data_win_system_severityValue":  "INFORMATION",
                                                  "data_win_eventdata_processGuid":  "{23c79bc1-1771-65bc-2800-000000001200}",
                                                  "rule_mitre_technique":  "Event Triggered Execution",
                                                  "rule_firedtimes":  8,
                                                  "data_win_system_systemTime":  "2024-02-01T22:13:30.6923405Z",
                                                  "rule_mail":  "false",
                                                  "log_type":  "wazuh_1",
                                                  "decoder_name":  "windows_eventchannel",
                                                  "data_win_eventdata_commandLine":  "taskhostw.exe ExploitGuardPolicy",
                                                  "data_win_system_processID":  "3080",
                                                  "data_win_system_channel":  "Microsoft-Windows-Sysmon/Operational",
                                                  "data_win_system_providerName":  "Microsoft-Windows-Sysmon",
                                                  "data_win_eventdata_processId":  "1748",
                                                  "data_win_system_version":  "5",
                                                  "data_win_system_providerGuid":  "{5770385f-c22a-43e0-bf4c-06f5698ffbd9}",
                                                  "timestamp":  "2024-02-01 22:13:35.718",
                                                  "data_win_eventdata_parentCommandLine":  "C:\\\\Windows\\\\system32\\\\svchost.exe -k netsvcs -p -s Schedule",
                                                  "data_win_system_opcode":  "0",
                                                  "gl2_processing_error":  "Replaced invalid timestamp value in message \u003c24b01240-c14f-11ee-b713-000c292285df\u003e with current time - Value \u003c2024-02-01T17:13:32.424-0500\u003e caused exception: Invalid format: \"2024-02-01T17:13:32.424-0500\" is malformed at \"T17:13:32.424-0500\".",
                                                  "data_win_eventdata_terminalSessionId":  "0",
                                                  
                                                  "rule_id":  "100100",
                                                  "manager_name":  "wazuhmanager",
                                                  "data_win_eventdata_logonGuid":  "{23c79bc1-176d-65bc-e703-000000000000}",
                                                  "data_win_eventdata_logonId":  "0x3e7",
                                                  "location":  "EventChannel",
                                                  "data_win_system_message":  "\"Process Create:\r\nRuleName: -\r\nUtcTime: 2024-02-01 22:13:05.384\r\nProcessGuid: {23c79bc1-1771-65bc-2800-000000001200}\r\nProcessId: 1748\r\nImage: C:\\Windows\\System32\\taskhostw.exe\r\nFileVersion: 10.0.19041.3636 (WinBuild.160101.0800)\r\nDescription: Host Process for Windows Tasks\r\nProduct: Microsoft® Windows® Operating System\r\nCompany: Microsoft Corporation\r\nOriginalFileName: taskhostw.exe\r\nCommandLine: taskhostw.exe ExploitGuardPolicy\r\nCurrentDirectory: C:\\Windows\\system32\\\r\nUser: NT AUTHORITY\\SYSTEM\r\nLogonGuid: {23c79bc1-176d-65bc-e703-000000000000}\r\nLogonId: 0x3E7\r\nTerminalSessionId: 0\r\nIntegrityLevel: System\r\nHashes: SHA256=976BB3FB062818E9643EC7F65BE2F267B90F63BD9F8BE0E6212D131183136140\r\nParentProcessGuid: {23c79bc1-176f-65bc-1a00-000000001200}\r\nParentProcessId: 1220\r\nParentImage: C:\\Windows\\System32\\svchost.exe\r\nParentCommandLine: C:\\Windows\\system32\\svchost.exe -k netsvcs -p -s Schedule\r\nParentUser: NT AUTHORITY\\SYSTEM\"",
                                                  "data_win_eventdata_product":  "Microsoft® Windows® Operating System"
                                              }
                              },
                              {
                                  "_index":  "wazuh_alert_1_perfix_0",
                                  "_id":  "24b01241-c14f-11ee-b713-000c292285df",
                                  "_score":  1.0,
                                  "_source":  {
                                                  "data_win_eventdata_description":  "DXGI Adapter Cache",
                                                  "source_reserved_ip":  "true",
                                                  "data_win_system_eventRecordID":  "2010237",
                                                  "data_win_eventdata_user":  "NT AUTHORITY\\\\SYSTEM",
                                                  "agent_id":  "002",
                                                  "agent_name":  "DESKTOP-GJA3NM0",
                                                  "gl2_remote_ip":  "192.168.59.130",
                                                  "data_win_system_eventID":  "1",
                                                  "gl2_remote_port":  59614,
                                                  "source":  "192.168.59.130",
                                                  "gl2_source_input":  "65b67daf8ee8cf109aa47ccd",
                                                  "rule_level":  3,
                                                  "data_win_eventdata_originalFileName":  "DXGIAdapterCache.exe",
                                                  "data_win_eventdata_company":  "Microsoft Corporation",
                                                  "data_win_system_task":  "1",
                                                  "data_win_system_threadID":  "5564",
                                                  "rule_description":  "Sysmon - Event 1: Process creation DXGI Adapter Cache",
                                                  "data_win_eventdata_parentUser":  "NT AUTHORITY\\\\SYSTEM",
                                                  "gl2_source_node":  "90642c69-49a0-4566-8fcc-92a46421e216",
                                                  "id":  "1706825612.5521996",
                                                  "rule_mitre_tactic":  "Privilege Escalation, Persistence",
                                                  "gl2_accounted_message_size":  6550,
                                                  "data_win_eventdata_integrityLevel":  "System",
                                                  "data_win_eventdata_utcTime":  "2024-02-01 22:13:07.474",
                                                  "streams":  [
                                                                  "65b800c7ef47be2bbc6927a3"
                                                              ],
                                                  "rule_mitre_id":  "T1546",
                                                  "gl2_message_id":  "01HNKBR2B6ZE5TYT3W5P19RSVF",
                                                  "data_win_system_computer":  "DESKTOP-GJA3NM0",
                                                  "data_win_eventdata_currentDirectory":  "C:\\\\Windows\\\\system32\\\\",
                                                  "agent_ip_reserved_ip":  "true",
                                                  "data_win_eventdata_hashes":  "SHA256=3609BD5B679F18F2F47A28F29BBBE98ECC597D02CE74262948E7C8C1F31544C7",
                                                  "agent_ip":  "192.168.59.131",
                                                  "data_win_eventdata_image":  "C:\\\\Windows\\\\System32\\\\dxgiadaptercache.exe",
                                                  "rule_groups2":  "sysmon",
                                                  "rule_groups1":  "windows",
                                                  "rule_groups3":  "sysmon_event1",
                                                  "data_win_eventdata_parentProcessGuid":  "{23c79bc1-176f-65bc-1a00-000000001200}",
                                                  "true":  1706825613.0204949,
                                                  "data_win_eventdata_parentProcessId":  "1220",
                                                  "rule_groups":  "windows, sysmon, sysmon_event1, windows_sysmon_event1",
                                                  "data_win_system_keywords":  "0x8000000000000000",
                                                  "data_win_system_level":  "4",
                                                  "data_win_eventdata_fileVersion":  "10.0.19041.3636 (WinBuild.160101.0800)",
                                                  "data_win_eventdata_parentImage":  "C:\\\\Windows\\\\System32\\\\svchost.exe",
                                                  "data_win_system_severityValue":  "INFORMATION",
                                                  "data_win_eventdata_processGuid":  "{23c79bc1-1773-65bc-3000-000000001200}",
                                                  "rule_mitre_technique":  "Event Triggered Execution",
                                                  "rule_firedtimes":  9,
                                                  "data_win_system_systemTime":  "2024-02-01T22:13:30.7049417Z",
                                                  "rule_mail":  "false",
                                                  "log_type":  "wazuh_1",
                                                  "decoder_name":  "windows_eventchannel",
                                                  "data_win_eventdata_commandLine":  "\\\"C:\\\\Windows\\\\system32\\\\dxgiadaptercache.exe\\\"",
                                                  "data_win_system_processID":  "3080",
                                                  "data_win_system_channel":  "Microsoft-Windows-Sysmon/Operational",
                                                  "data_win_system_providerName":  "Microsoft-Windows-Sysmon",
                                                  "data_win_eventdata_processId":  "2080",
                                                  "data_win_system_version":  "5",
                                                  "data_win_system_providerGuid":  "{5770385f-c22a-43e0-bf4c-06f5698ffbd9}",
                                                  "timestamp":  "2024-02-01 22:13:35.718",
                                                  "data_win_eventdata_parentCommandLine":  "C:\\\\Windows\\\\system32\\\\svchost.exe -k netsvcs -p -s Schedule",
                                                  "data_win_system_opcode":  "0",
                                                  "gl2_processing_error":  "Replaced invalid timestamp value in message \u003c24b01241-c14f-11ee-b713-000c292285df\u003e with current time - Value \u003c2024-02-01T17:13:32.877-0500\u003e caused exception: Invalid format: \"2024-02-01T17:13:32.877-0500\" is malformed at \"T17:13:32.877-0500\".",
                                                  "data_win_eventdata_terminalSessionId":  "0",
                                                  
                                                  "rule_id":  "100100",
                                                  "manager_name":  "wazuhmanager",
                                                  "data_win_eventdata_logonGuid":  "{23c79bc1-176d-65bc-e703-000000000000}",
                                                  "data_win_eventdata_logonId":  "0x3e7",
                                                  "location":  "EventChannel",
                                                  "data_win_system_message":  "\"Process Create:\r\nRuleName: -\r\nUtcTime: 2024-02-01 22:13:07.474\r\nProcessGuid: {23c79bc1-1773-65bc-3000-000000001200}\r\nProcessId: 2080\r\nImage: C:\\Windows\\System32\\dxgiadaptercache.exe\r\nFileVersion: 10.0.19041.3636 (WinBuild.160101.0800)\r\nDescription: DXGI Adapter Cache\r\nProduct: Microsoft® Windows® Operating System\r\nCompany: Microsoft Corporation\r\nOriginalFileName: DXGIAdapterCache.exe\r\nCommandLine: \"C:\\Windows\\system32\\dxgiadaptercache.exe\"\r\nCurrentDirectory: C:\\Windows\\system32\\\r\nUser: NT AUTHORITY\\SYSTEM\r\nLogonGuid: {23c79bc1-176d-65bc-e703-000000000000}\r\nLogonId: 0x3E7\r\nTerminalSessionId: 0\r\nIntegrityLevel: System\r\nHashes: SHA256=3609BD5B679F18F2F47A28F29BBBE98ECC597D02CE74262948E7C8C1F31544C7\r\nParentProcessGuid: {23c79bc1-176f-65bc-1a00-000000001200}\r\nParentProcessId: 1220\r\nParentImage: C:\\Windows\\System32\\svchost.exe\r\nParentCommandLine: C:\\Windows\\system32\\svchost.exe -k netsvcs -p -s Schedule\r\nParentUser: NT AUTHORITY\\SYSTEM\"",
                                                  "data_win_eventdata_product":  "Microsoft® Windows® Operating System"
                                              }
                              },
                              {
                                  "_index":  "wazuh_alert_1_perfix_0",
                                  "_id":  "24b01242-c14f-11ee-b713-000c292285df",
                                  "_score":  1.0,
                                  "_source":  {
                                                  "data_win_eventdata_description":  "Spooler SubSystem App",
                                                  "source_reserved_ip":  "true",
                                                  "data_win_system_eventRecordID":  "2010244",
                                                  "data_win_eventdata_user":  "NT AUTHORITY\\\\SYSTEM",
                                                  "agent_id":  "002",
                                                  "agent_name":  "DESKTOP-GJA3NM0",
                                                  "gl2_remote_ip":  "192.168.59.130",
                                                  "data_win_system_eventID":  "1",
                                                  "gl2_remote_port":  59614,
                                                  "source":  "192.168.59.130",
                                                  "gl2_source_input":  "65b67daf8ee8cf109aa47ccd",
                                                  "rule_level":  3,
                                                  "data_win_eventdata_originalFileName":  "spoolsv.exe",
                                                  "data_win_eventdata_company":  "Microsoft Corporation",
                                                  "data_win_system_task":  "1",
                                                  "data_win_system_threadID":  "5564",
                                                  "rule_description":  "Sysmon - Event 1: Process creation Spooler SubSystem App",
                                                  "data_win_eventdata_parentUser":  "NT AUTHORITY\\\\SYSTEM",
                                                  "gl2_source_node":  "90642c69-49a0-4566-8fcc-92a46421e216",
                                                  "id":  "1706825613.5527427",
                                                  "rule_mitre_tactic":  "Privilege Escalation, Persistence",
                                                  "gl2_accounted_message_size":  6343,
                                                  "data_win_eventdata_integrityLevel":  "System",
                                                  "data_win_eventdata_utcTime":  "2024-02-01 22:13:08.154",
                                                  "streams":  [
                                                                  "65b800c7ef47be2bbc6927a3"
                                                              ],
                                                  "rule_mitre_id":  "T1546",
                                                  "gl2_message_id":  "01HNKBR2B6PBDK03KZFETNPDP9",
                                                  "data_win_system_computer":  "DESKTOP-GJA3NM0",
                                                  "data_win_eventdata_currentDirectory":  "C:\\\\Windows\\\\system32\\\\",
                                                  "agent_ip_reserved_ip":  "true",
                                                  "data_win_eventdata_hashes":  "SHA256=10CD8F6DBE6F716F757CB2544F1634879B5CF6AE9152AF6CCACDFEE393A29B7A",
                                                  "agent_ip":  "192.168.59.131",
                                                  "data_win_eventdata_image":  "C:\\\\Windows\\\\System32\\\\spoolsv.exe",
                                                  "rule_groups2":  "sysmon",
                                                  "rule_groups1":  "windows",
                                                  "rule_groups3":  "sysmon_event1",
                                                  "data_win_eventdata_parentProcessGuid":  "{23c79bc1-176d-65bc-0a00-000000001200}",
                                                  "true":  1706825613.4432759,
                                                  "data_win_eventdata_parentProcessId":  "668",
                                                  "rule_groups":  "windows, sysmon, sysmon_event1, windows_sysmon_event1",
                                                  "data_win_system_keywords":  "0x8000000000000000",
                                                  "data_win_system_level":  "4",
                                                  "data_win_eventdata_fileVersion":  "10.0.19041.3636 (WinBuild.160101.0800)",
                                                  "data_win_eventdata_parentImage":  "C:\\\\Windows\\\\System32\\\\services.exe",
                                                  "data_win_system_severityValue":  "INFORMATION",
                                                  "data_win_eventdata_processGuid":  "{23c79bc1-1774-65bc-3700-000000001200}",
                                                  "rule_mitre_technique":  "Event Triggered Execution",
                                                  "rule_firedtimes":  10,
                                                  "data_win_system_systemTime":  "2024-02-01T22:13:30.7123577Z",
                                                  "rule_mail":  "false",
                                                  "log_type":  "wazuh_1",
                                                  "decoder_name":  "windows_eventchannel",
                                                  "data_win_eventdata_commandLine":  "C:\\\\Windows\\\\System32\\\\spoolsv.exe",
                                                  "data_win_system_processID":  "3080",
                                                  "data_win_system_channel":  "Microsoft-Windows-Sysmon/Operational",
                                                  "data_win_system_providerName":  "Microsoft-Windows-Sysmon",
                                                  "data_win_eventdata_processId":  "2388",
                                                  "data_win_system_version":  "5",
                                                  "data_win_system_providerGuid":  "{5770385f-c22a-43e0-bf4c-06f5698ffbd9}",
                                                  "timestamp":  "2024-02-01 22:13:35.718",
                                                  "data_win_eventdata_parentCommandLine":  "C:\\\\Windows\\\\system32\\\\services.exe",
                                                  "data_win_system_opcode":  "0",
                                                  "gl2_processing_error":  "Replaced invalid timestamp value in message \u003c24b01242-c14f-11ee-b713-000c292285df\u003e with current time - Value \u003c2024-02-01T17:13:33.252-0500\u003e caused exception: Invalid format: \"2024-02-01T17:13:33.252-0500\" is malformed at \"T17:13:33.252-0500\".",
                                                  "data_win_eventdata_terminalSessionId":  "0",
                                                  
                                                  "rule_id":  "100100",
                                                  "manager_name":  "wazuhmanager",
                                                  "data_win_eventdata_logonGuid":  "{23c79bc1-176d-65bc-e703-000000000000}",
                                                  "data_win_eventdata_logonId":  "0x3e7",
                                                  "location":  "EventChannel",
                                                  "data_win_system_message":  "\"Process Create:\r\nRuleName: -\r\nUtcTime: 2024-02-01 22:13:08.154\r\nProcessGuid: {23c79bc1-1774-65bc-3700-000000001200}\r\nProcessId: 2388\r\nImage: C:\\Windows\\System32\\spoolsv.exe\r\nFileVersion: 10.0.19041.3636 (WinBuild.160101.0800)\r\nDescription: Spooler SubSystem App\r\nProduct: Microsoft® Windows® Operating System\r\nCompany: Microsoft Corporation\r\nOriginalFileName: spoolsv.exe\r\nCommandLine: C:\\Windows\\System32\\spoolsv.exe\r\nCurrentDirectory: C:\\Windows\\system32\\\r\nUser: NT AUTHORITY\\SYSTEM\r\nLogonGuid: {23c79bc1-176d-65bc-e703-000000000000}\r\nLogonId: 0x3E7\r\nTerminalSessionId: 0\r\nIntegrityLevel: System\r\nHashes: SHA256=10CD8F6DBE6F716F757CB2544F1634879B5CF6AE9152AF6CCACDFEE393A29B7A\r\nParentProcessGuid: {23c79bc1-176d-65bc-0a00-000000001200}\r\nParentProcessId: 668\r\nParentImage: C:\\Windows\\System32\\services.exe\r\nParentCommandLine: C:\\Windows\\system32\\services.exe\r\nParentUser: NT AUTHORITY\\SYSTEM\"",
                                                  "data_win_eventdata_product":  "Microsoft® Windows® Operating System"
                                              }
                              },
                              {
                                  "_index":  "wazuh_alert_1_perfix_0",
                                  "_id":  "24b14ac3-c14f-11ee-b713-000c292285df",
                                  "_score":  1.0,
                                  "_source":  {
                                                  "data_win_eventdata_description":  "Console Window Host",
                                                  "source_reserved_ip":  "true",
                                                  "data_win_system_eventRecordID":  "2010270",
                                                  "data_win_eventdata_user":  "NT AUTHORITY\\\\LOCAL SERVICE",
                                                  "agent_id":  "002",
                                                  "agent_name":  "DESKTOP-GJA3NM0",
                                                  "gl2_remote_ip":  "192.168.59.130",
                                                  "data_win_system_eventID":  "1",
                                                  "gl2_remote_port":  59614,
                                                  "source":  "192.168.59.130",
                                                  "gl2_source_input":  "65b67daf8ee8cf109aa47ccd",
                                                  "rule_level":  3,
                                                  "data_win_eventdata_originalFileName":  "CONHOST.EXE",
                                                  "data_win_eventdata_company":  "Microsoft Corporation",
                                                  "data_win_system_task":  "1",
                                                  "data_win_system_threadID":  "5564",
                                                  "rule_description":  "Suspicious Windows cmd shell execution",
                                                  "data_win_eventdata_parentUser":  "NT AUTHORITY\\\\LOCAL SERVICE",
                                                  "gl2_source_node":  "90642c69-49a0-4566-8fcc-92a46421e216",
                                                  "id":  "1706825614.5602939",
                                                  "rule_mitre_tactic":  "Discovery, Execution",
                                                  "gl2_accounted_message_size":  6648,
                                                  "data_win_eventdata_integrityLevel":  "System",
                                                  "data_win_eventdata_utcTime":  "2024-02-01 22:13:12.383",
                                                  "streams":  [
                                                                  "65b800c7ef47be2bbc6927a3"
                                                              ],
                                                  "rule_mitre_id":  "T1087, T1059.003",
                                                  "gl2_message_id":  "01HNKBR2BDMY84TY2J3HA3ZTF4",
                                                  "data_win_system_computer":  "DESKTOP-GJA3NM0",
                                                  "data_win_eventdata_currentDirectory":  "C:\\\\Windows",
                                                  "agent_ip_reserved_ip":  "true",
                                                  "data_win_eventdata_hashes":  "SHA256=C43CF46192DA061DD6169E55AAC4D2D08A6C33C039A7DAC0D88AA897661CBC87",
                                                  "agent_ip":  "192.168.59.131",
                                                  "data_win_eventdata_image":  "C:\\\\Windows\\\\System32\\\\conhost.exe",
                                                  "rule_groups2":  "sysmon_eid1_detections",
                                                  "rule_groups1":  "sysmon",
                                                  "rule_groups3":  "windows",
                                                  "data_win_eventdata_parentProcessGuid":  "{23c79bc1-1778-65bc-4e00-000000001200}",
                                                  "true":  1706825614.867336,
                                                  "data_win_eventdata_parentProcessId":  "3108",
                                                  "rule_groups":  "sysmon, sysmon_eid1_detections, windows",
                                                  "data_win_system_keywords":  "0x8000000000000000",
                                                  "data_win_system_level":  "4",
                                                  "data_win_eventdata_fileVersion":  "10.0.19041.3636 (WinBuild.160101.0800)",
                                                  "data_win_eventdata_parentImage":  "C:\\\\Windows\\\\System32\\\\cmd.exe",
                                                  "data_win_system_severityValue":  "INFORMATION",
                                                  "data_win_eventdata_processGuid":  "{23c79bc1-1778-65bc-5200-000000001200}",
                                                  "rule_mitre_technique":  "Account Discovery, Windows Command Shell",
                                                  "rule_firedtimes":  1,
                                                  "data_win_system_systemTime":  "2024-02-01T22:13:30.7371859Z",
                                                  "rule_mail":  "false",
                                                  "log_type":  "wazuh_1",
                                                  "decoder_name":  "windows_eventchannel",
                                                  "data_win_eventdata_commandLine":  "\\\\??\\\\C:\\\\Windows\\\\system32\\\\conhost.exe 0xffffffff -ForceV1",
                                                  "data_win_system_processID":  "3080",
                                                  "data_win_system_channel":  "Microsoft-Windows-Sysmon/Operational",
                                                  "data_win_system_providerName":  "Microsoft-Windows-Sysmon",
                                                  "data_win_eventdata_processId":  "3184",
                                                  "data_win_system_version":  "5",
                                                  "data_win_system_providerGuid":  "{5770385f-c22a-43e0-bf4c-06f5698ffbd9}",
                                                  "timestamp":  "2024-02-01 22:13:35.725",
                                                  "data_win_eventdata_parentCommandLine":  "C:\\\\Windows\\\\system32\\\\cmd.exe /c \\\"\\\"C:/Program Files (x86)/Acunetix/pg/bin/postgres.exe\\\" -V\\\"",
                                                  "data_win_system_opcode":  "0",
                                                  "gl2_processing_error":  "Replaced invalid timestamp value in message \u003c24b14ac3-c14f-11ee-b713-000c292285df\u003e with current time - Value \u003c2024-02-01T17:13:34.864-0500\u003e caused exception: Invalid format: \"2024-02-01T17:13:34.864-0500\" is malformed at \"T17:13:34.864-0500\".",
                                                  "data_win_eventdata_terminalSessionId":  "0",
                                                  
                                                  "rule_id":  "92032",
                                                  "manager_name":  "wazuhmanager",
                                                  "data_win_eventdata_logonGuid":  "{23c79bc1-176f-65bc-e503-000000000000}",
                                                  "data_win_eventdata_logonId":  "0x3e5",
                                                  "location":  "EventChannel",
                                                  "data_win_system_message":  "\"Process Create:\r\nRuleName: -\r\nUtcTime: 2024-02-01 22:13:12.383\r\nProcessGuid: {23c79bc1-1778-65bc-5200-000000001200}\r\nProcessId: 3184\r\nImage: C:\\Windows\\System32\\conhost.exe\r\nFileVersion: 10.0.19041.3636 (WinBuild.160101.0800)\r\nDescription: Console Window Host\r\nProduct: Microsoft® Windows® Operating System\r\nCompany: Microsoft Corporation\r\nOriginalFileName: CONHOST.EXE\r\nCommandLine: \\??\\C:\\Windows\\system32\\conhost.exe 0xffffffff -ForceV1\r\nCurrentDirectory: C:\\Windows\r\nUser: NT AUTHORITY\\LOCAL SERVICE\r\nLogonGuid: {23c79bc1-176f-65bc-e503-000000000000}\r\nLogonId: 0x3E5\r\nTerminalSessionId: 0\r\nIntegrityLevel: System\r\nHashes: SHA256=C43CF46192DA061DD6169E55AAC4D2D08A6C33C039A7DAC0D88AA897661CBC87\r\nParentProcessGuid: {23c79bc1-1778-65bc-4e00-000000001200}\r\nParentProcessId: 3108\r\nParentImage: C:\\Windows\\System32\\cmd.exe\r\nParentCommandLine: C:\\Windows\\system32\\cmd.exe /c \"\"C:/Program Files (x86)/Acunetix/pg/bin/postgres.exe\" -V\"\r\nParentUser: NT AUTHORITY\\LOCAL SERVICE\"",
                                                  "data_win_eventdata_product":  "Microsoft® Windows® Operating System"
                                              }
                              },
                              {
                                  "_index":  "wazuh_alert_1_perfix_0",
                                  "_id":  "24b1e700-c14f-11ee-b713-000c292285df",
                                  "_score":  1.0,
                                  "_source":  {
                                                  "data_win_eventdata_description":  "Console Window Host",
                                                  "source_reserved_ip":  "true",
                                                  "data_win_system_eventRecordID":  "2010283",
                                                  "data_win_eventdata_user":  "NT AUTHORITY\\\\SYSTEM",
                                                  "agent_id":  "002",
                                                  "agent_name":  "DESKTOP-GJA3NM0",
                                                  "gl2_remote_ip":  "192.168.59.130",
                                                  "data_win_system_eventID":  "1",
                                                  "gl2_remote_port":  59614,
                                                  "source":  "192.168.59.130",
                                                  "gl2_source_input":  "65b67daf8ee8cf109aa47ccd",
                                                  "rule_level":  3,
                                                  "data_win_eventdata_originalFileName":  "CONHOST.EXE",
                                                  "data_win_eventdata_company":  "Microsoft Corporation",
                                                  "data_win_system_task":  "1",
                                                  "data_win_system_threadID":  "5564",
                                                  "rule_description":  "Sysmon - Event 1: Process creation Console Window Host",
                                                  "data_win_eventdata_parentUser":  "NT AUTHORITY\\\\SYSTEM",
                                                  "gl2_source_node":  "90642c69-49a0-4566-8fcc-92a46421e216",
                                                  "id":  "1706825615.5663012",
                                                  "rule_mitre_tactic":  "Privilege Escalation, Persistence",
                                                  "gl2_accounted_message_size":  6946,
                                                  "data_win_eventdata_integrityLevel":  "System",
                                                  "data_win_eventdata_utcTime":  "2024-02-01 22:13:17.191",
                                                  "streams":  [
                                                                  "65b800c7ef47be2bbc6927a3"
                                                              ],
                                                  "rule_mitre_id":  "T1546",
                                                  "gl2_message_id":  "01HNKBR2BMWDR8T9VNJM5G3M39",
                                                  "data_win_system_computer":  "DESKTOP-GJA3NM0",
                                                  "data_win_eventdata_currentDirectory":  "C:\\\\Windows",
                                                  "agent_ip_reserved_ip":  "true",
                                                  "data_win_eventdata_hashes":  "SHA256=C43CF46192DA061DD6169E55AAC4D2D08A6C33C039A7DAC0D88AA897661CBC87",
                                                  "agent_ip":  "192.168.59.131",
                                                  "data_win_eventdata_image":  "C:\\\\Windows\\\\System32\\\\conhost.exe",
                                                  "rule_groups2":  "sysmon",
                                                  "rule_groups1":  "windows",
                                                  "rule_groups3":  "sysmon_event1",
                                                  "data_win_eventdata_parentProcessGuid":  "{23c79bc1-1777-65bc-4a00-000000001200}",
                                                  "true":  1706825615.37721,
                                                  "data_win_eventdata_parentProcessId":  "3064",
                                                  "rule_groups":  "windows, sysmon, sysmon_event1, windows_sysmon_event1",
                                                  "data_win_system_keywords":  "0x8000000000000000",
                                                  "data_win_system_level":  "4",
                                                  "data_win_eventdata_fileVersion":  "10.0.19041.3636 (WinBuild.160101.0800)",
                                                  "data_win_eventdata_parentImage":  "C:\\\\ProgramData\\\\Microsoft\\\\Windows Defender\\\\Platform\\\\4.18.23110.3-0\\\\MpCmdRun.exe",
                                                  "data_win_system_severityValue":  "INFORMATION",
                                                  "data_win_eventdata_processGuid":  "{23c79bc1-177d-65bc-6000-000000001200}",
                                                  "rule_mitre_technique":  "Event Triggered Execution",
                                                  "rule_firedtimes":  31,
                                                  "data_win_system_systemTime":  "2024-02-01T22:13:30.7472693Z",
                                                  "rule_mail":  "false",
                                                  "log_type":  "wazuh_1",
                                                  "decoder_name":  "windows_eventchannel",
                                                  "data_win_eventdata_commandLine":  "\\\\??\\\\C:\\\\Windows\\\\system32\\\\conhost.exe 0xffffffff -ForceV1",
                                                  "data_win_system_processID":  "3080",
                                                  "data_win_system_channel":  "Microsoft-Windows-Sysmon/Operational",
                                                  "data_win_system_providerName":  "Microsoft-Windows-Sysmon",
                                                  "data_win_eventdata_processId":  "2660",
                                                  "data_win_system_version":  "5",
                                                  "data_win_system_providerGuid":  "{5770385f-c22a-43e0-bf4c-06f5698ffbd9}",
                                                  "timestamp":  "2024-02-01 22:13:35.732",
                                                  "data_win_eventdata_parentCommandLine":  "\\\"C:\\\\ProgramData\\\\Microsoft\\\\Windows Defender\\\\platform\\\\4.18.23110.3-0\\\\MpCmdRun.exe\\\" -IdleTask -TaskName WdVerification",
                                                  "data_win_system_opcode":  "0",
                                                  "gl2_processing_error":  "Replaced invalid timestamp value in message \u003c24b1e700-c14f-11ee-b713-000c292285df\u003e with current time - Value \u003c2024-02-01T17:13:35.367-0500\u003e caused exception: Invalid format: \"2024-02-01T17:13:35.367-0500\" is malformed at \"T17:13:35.367-0500\".",
                                                  "data_win_eventdata_terminalSessionId":  "0",
                                                  
                                                  "rule_id":  "100100",
                                                  "manager_name":  "wazuhmanager",
                                                  "data_win_eventdata_logonGuid":  "{23c79bc1-176d-65bc-e703-000000000000}",
                                                  "data_win_eventdata_logonId":  "0x3e7",
                                                  "location":  "EventChannel",
                                                  "data_win_system_message":  "\"Process Create:\r\nRuleName: -\r\nUtcTime: 2024-02-01 22:13:17.191\r\nProcessGuid: {23c79bc1-177d-65bc-6000-000000001200}\r\nProcessId: 2660\r\nImage: C:\\Windows\\System32\\conhost.exe\r\nFileVersion: 10.0.19041.3636 (WinBuild.160101.0800)\r\nDescription: Console Window Host\r\nProduct: Microsoft® Windows® Operating System\r\nCompany: Microsoft Corporation\r\nOriginalFileName: CONHOST.EXE\r\nCommandLine: \\??\\C:\\Windows\\system32\\conhost.exe 0xffffffff -ForceV1\r\nCurrentDirectory: C:\\Windows\r\nUser: NT AUTHORITY\\SYSTEM\r\nLogonGuid: {23c79bc1-176d-65bc-e703-000000000000}\r\nLogonId: 0x3E7\r\nTerminalSessionId: 0\r\nIntegrityLevel: System\r\nHashes: SHA256=C43CF46192DA061DD6169E55AAC4D2D08A6C33C039A7DAC0D88AA897661CBC87\r\nParentProcessGuid: {23c79bc1-1777-65bc-4a00-000000001200}\r\nParentProcessId: 3064\r\nParentImage: C:\\ProgramData\\Microsoft\\Windows Defender\\Platform\\4.18.23110.3-0\\MpCmdRun.exe\r\nParentCommandLine: \"C:\\ProgramData\\Microsoft\\Windows Defender\\platform\\4.18.23110.3-0\\MpCmdRun.exe\" -IdleTask -TaskName WdVerification\r\nParentUser: NT AUTHORITY\\SYSTEM\"",
                                                  "data_win_eventdata_product":  "Microsoft® Windows® Operating System"
                                              }
                              },
                              {
                                  "_index":  "wazuh_alert_1_perfix_0",
                                  "_id":  "27aa8d96-c14f-11ee-b713-000c292285df",
                                  "_score":  1.0,
                                  "_source":  {
                                                  "data_win_eventdata_description":  "Host Process for Windows Tasks",
                                                  "source_reserved_ip":  "true",
                                                  "data_win_system_eventRecordID":  "2010303",
                                                  "data_win_eventdata_user":  "DESKTOP-GJA3NM0\\\\Administrator",
                                                  "agent_id":  "002",
                                                  "agent_name":  "DESKTOP-GJA3NM0",
                                                  "gl2_remote_ip":  "192.168.59.130",
                                                  "data_win_system_eventID":  "1",
                                                  "gl2_remote_port":  59624,
                                                  "source":  "192.168.59.130",
                                                  "gl2_source_input":  "65b67daf8ee8cf109aa47ccd",
                                                  "rule_level":  3,
                                                  "data_win_eventdata_originalFileName":  "taskhostw.exe",
                                                  "data_win_eventdata_company":  "Microsoft Corporation",
                                                  "data_win_system_task":  "1",
                                                  "data_win_system_threadID":  "5564",
                                                  "rule_description":  "Sysmon - Event 1: Process creation Host Process for Windows Tasks",
                                                  "data_win_eventdata_parentUser":  "NT AUTHORITY\\\\SYSTEM",
                                                  "gl2_source_node":  "90642c69-49a0-4566-8fcc-92a46421e216",
                                                  "id":  "1706825616.5723382",
                                                  "rule_mitre_tactic":  "Privilege Escalation, Persistence",
                                                  "gl2_accounted_message_size":  6621,
                                                  "data_win_eventdata_integrityLevel":  "High",
                                                  "data_win_eventdata_utcTime":  "2024-02-01 22:13:20.130",
                                                  "streams":  [
                                                                  "65b800c7ef47be2bbc6927a3"
                                                              ],
                                                  "rule_mitre_id":  "T1546",
                                                  "gl2_message_id":  "01HNKBR77APNXY9923H9V3EFFZ",
                                                  "data_win_system_computer":  "DESKTOP-GJA3NM0",
                                                  "data_win_eventdata_currentDirectory":  "C:\\\\Windows\\\\system32\\\\",
                                                  "agent_ip_reserved_ip":  "true",
                                                  "data_win_eventdata_hashes":  "SHA256=976BB3FB062818E9643EC7F65BE2F267B90F63BD9F8BE0E6212D131183136140",
                                                  "agent_ip":  "192.168.59.131",
                                                  "data_win_eventdata_image":  "C:\\\\Windows\\\\System32\\\\taskhostw.exe",
                                                  "rule_groups2":  "sysmon",
                                                  "rule_groups1":  "windows",
                                                  "rule_groups3":  "sysmon_event1",
                                                  "data_win_eventdata_parentProcessGuid":  "{23c79bc1-176f-65bc-1a00-000000001200}",
                                                  "true":  1706825616.48056,
                                                  "data_win_eventdata_parentProcessId":  "1220",
                                                  "rule_groups":  "windows, sysmon, sysmon_event1, windows_sysmon_event1",
                                                  "data_win_system_keywords":  "0x8000000000000000",
                                                  "data_win_system_level":  "4",
                                                  "data_win_eventdata_fileVersion":  "10.0.19041.3636 (WinBuild.160101.0800)",
                                                  "data_win_eventdata_parentImage":  "C:\\\\Windows\\\\System32\\\\svchost.exe",
                                                  "data_win_system_severityValue":  "INFORMATION",
                                                  "data_win_eventdata_processGuid":  "{23c79bc1-1780-65bc-6c00-000000001200}",
                                                  "rule_mitre_technique":  "Event Triggered Execution",
                                                  "rule_firedtimes":  40,
                                                  "data_win_system_systemTime":  "2024-02-01T22:13:30.8181908Z",
                                                  "rule_mail":  "false",
                                                  "log_type":  "wazuh_1",
                                                  "decoder_name":  "windows_eventchannel",
                                                  "data_win_eventdata_commandLine":  "taskhostw.exe {222A245B-E637-4AE9-A93F-A59CA119A75E}",
                                                  "data_win_system_processID":  "3080",
                                                  "data_win_system_channel":  "Microsoft-Windows-Sysmon/Operational",
                                                  "data_win_system_providerName":  "Microsoft-Windows-Sysmon",
                                                  "data_win_eventdata_processId":  "4360",
                                                  "data_win_system_version":  "5",
                                                  "data_win_system_providerGuid":  "{5770385f-c22a-43e0-bf4c-06f5698ffbd9}",
                                                  "timestamp":  "2024-02-01 22:13:40.714",
                                                  "data_win_eventdata_parentCommandLine":  "C:\\\\Windows\\\\system32\\\\svchost.exe -k netsvcs -p -s Schedule",
                                                  "data_win_system_opcode":  "0",
                                                  "gl2_processing_error":  "Replaced invalid timestamp value in message \u003c27aa8d96-c14f-11ee-b713-000c292285df\u003e with current time - Value \u003c2024-02-01T17:13:36.474-0500\u003e caused exception: Invalid format: \"2024-02-01T17:13:36.474-0500\" is malformed at \"T17:13:36.474-0500\".",
                                                  "data_win_eventdata_terminalSessionId":  "1",
                                                  
                                                  "rule_id":  "100100",
                                                  "manager_name":  "wazuhmanager",
                                                  "data_win_eventdata_logonGuid":  "{23c79bc1-1779-65bc-0c92-020000000000}",
                                                  "data_win_eventdata_logonId":  "0x2920c",
                                                  "location":  "EventChannel",
                                                  "data_win_system_message":  "\"Process Create:\r\nRuleName: -\r\nUtcTime: 2024-02-01 22:13:20.130\r\nProcessGuid: {23c79bc1-1780-65bc-6c00-000000001200}\r\nProcessId: 4360\r\nImage: C:\\Windows\\System32\\taskhostw.exe\r\nFileVersion: 10.0.19041.3636 (WinBuild.160101.0800)\r\nDescription: Host Process for Windows Tasks\r\nProduct: Microsoft® Windows® Operating System\r\nCompany: Microsoft Corporation\r\nOriginalFileName: taskhostw.exe\r\nCommandLine: taskhostw.exe {222A245B-E637-4AE9-A93F-A59CA119A75E}\r\nCurrentDirectory: C:\\Windows\\system32\\\r\nUser: DESKTOP-GJA3NM0\\Administrator\r\nLogonGuid: {23c79bc1-1779-65bc-0c92-020000000000}\r\nLogonId: 0x2920C\r\nTerminalSessionId: 1\r\nIntegrityLevel: High\r\nHashes: SHA256=976BB3FB062818E9643EC7F65BE2F267B90F63BD9F8BE0E6212D131183136140\r\nParentProcessGuid: {23c79bc1-176f-65bc-1a00-000000001200}\r\nParentProcessId: 1220\r\nParentImage: C:\\Windows\\System32\\svchost.exe\r\nParentCommandLine: C:\\Windows\\system32\\svchost.exe -k netsvcs -p -s Schedule\r\nParentUser: NT AUTHORITY\\SYSTEM\"",
                                                  "data_win_eventdata_product":  "Microsoft® Windows® Operating System"
                                              }
                              },
                              {
                                  "_index":  "wazuh_alert_1_perfix_0",
                                  "_id":  "27aa3f70-c14f-11ee-b713-000c292285df",
                                  "_score":  1.0,
                                  "_source":  {
                                                  "data_win_eventdata_description":  "Console Window Host",
                                                  "source_reserved_ip":  "true",
                                                  "data_win_system_eventRecordID":  "2010296",
                                                  "data_win_eventdata_user":  "NT AUTHORITY\\\\LOCAL SERVICE",
                                                  "agent_id":  "002",
                                                  "agent_name":  "DESKTOP-GJA3NM0",
                                                  "gl2_remote_ip":  "192.168.59.130",
                                                  "data_win_system_eventID":  "1",
                                                  "gl2_remote_port":  59624,
                                                  "source":  "192.168.59.130",
                                                  "gl2_source_input":  "65b67daf8ee8cf109aa47ccd",
                                                  "rule_level":  3,
                                                  "data_win_eventdata_originalFileName":  "CONHOST.EXE",
                                                  "data_win_eventdata_company":  "Microsoft Corporation",
                                                  "data_win_system_task":  "1",
                                                  "data_win_system_threadID":  "5564",
                                                  "rule_description":  "Sysmon - Event 1: Process creation Console Window Host",
                                                  "data_win_eventdata_parentUser":  "NT AUTHORITY\\\\LOCAL SERVICE",
                                                  "gl2_source_node":  "90642c69-49a0-4566-8fcc-92a46421e216",
                                                  "id":  "1706825615.5706869",
                                                  "rule_mitre_tactic":  "Privilege Escalation, Persistence",
                                                  "gl2_accounted_message_size":  6792,
                                                  "data_win_eventdata_integrityLevel":  "System",
                                                  "data_win_eventdata_utcTime":  "2024-02-01 22:13:18.839",
                                                  "streams":  [
                                                                  "65b800c7ef47be2bbc6927a3"
                                                              ],
                                                  "rule_mitre_id":  "T1546",
                                                  "gl2_message_id":  "01HNKBR77BSBD6TQMDYT6T298G",
                                                  "data_win_system_computer":  "DESKTOP-GJA3NM0",
                                                  "data_win_eventdata_currentDirectory":  "C:\\\\Windows",
                                                  "agent_ip_reserved_ip":  "true",
                                                  "data_win_eventdata_hashes":  "SHA256=C43CF46192DA061DD6169E55AAC4D2D08A6C33C039A7DAC0D88AA897661CBC87",
                                                  "agent_ip":  "192.168.59.131",
                                                  "data_win_eventdata_image":  "C:\\\\Windows\\\\System32\\\\conhost.exe",
                                                  "rule_groups2":  "sysmon",
                                                  "rule_groups1":  "windows",
                                                  "rule_groups3":  "sysmon_event1",
                                                  "data_win_eventdata_parentProcessGuid":  "{23c79bc1-177e-65bc-6500-000000001200}",
                                                  "true":  1706825616.021668,
                                                  "data_win_eventdata_parentProcessId":  "4164",
                                                  "rule_groups":  "windows, sysmon, sysmon_event1, windows_sysmon_event1",
                                                  "data_win_system_keywords":  "0x8000000000000000",
                                                  "data_win_system_level":  "4",
                                                  "data_win_eventdata_fileVersion":  "10.0.19041.3636 (WinBuild.160101.0800)",
                                                  "data_win_eventdata_parentImage":  "C:\\\\Program Files (x86)\\\\Acunetix\\\\pg\\\\bin\\\\postgres.exe",
                                                  "data_win_system_severityValue":  "INFORMATION",
                                                  "data_win_eventdata_processGuid":  "{23c79bc1-177e-65bc-6600-000000001200}",
                                                  "rule_mitre_technique":  "Event Triggered Execution",
                                                  "rule_firedtimes":  37,
                                                  "data_win_system_systemTime":  "2024-02-01T22:13:30.7540019Z",
                                                  "rule_mail":  "false",
                                                  "log_type":  "wazuh_1",
                                                  "decoder_name":  "windows_eventchannel",
                                                  "data_win_eventdata_commandLine":  "\\\\??\\\\C:\\\\Windows\\\\system32\\\\conhost.exe 0xffffffff -ForceV1",
                                                  "data_win_system_processID":  "3080",
                                                  "data_win_system_channel":  "Microsoft-Windows-Sysmon/Operational",
                                                  "data_win_system_providerName":  "Microsoft-Windows-Sysmon",
                                                  "data_win_eventdata_processId":  "4176",
                                                  "data_win_system_version":  "5",
                                                  "data_win_system_providerGuid":  "{5770385f-c22a-43e0-bf4c-06f5698ffbd9}",
                                                  "timestamp":  "2024-02-01 22:13:40.715",
                                                  "data_win_eventdata_parentCommandLine":  "\\\"C:\\\\Program Files (x86)\\\\Acunetix\\\\pg\\\\bin\\\\postgres.exe\\\" -D \\\"C:\\\\ProgramData\\\\Acunetix\\\\db\\\"",
                                                  "data_win_system_opcode":  "0",
                                                  "gl2_processing_error":  "Replaced invalid timestamp value in message \u003c27aa3f70-c14f-11ee-b713-000c292285df\u003e with current time - Value \u003c2024-02-01T17:13:35.808-0500\u003e caused exception: Invalid format: \"2024-02-01T17:13:35.808-0500\" is malformed at \"T17:13:35.808-0500\".",
                                                  "data_win_eventdata_terminalSessionId":  "0",
                                                  
                                                  "rule_id":  "100100",
                                                  "manager_name":  "wazuhmanager",
                                                  "data_win_eventdata_logonGuid":  "{23c79bc1-176f-65bc-e503-000000000000}",
                                                  "data_win_eventdata_logonId":  "0x3e5",
                                                  "location":  "EventChannel",
                                                  "data_win_system_message":  "\"Process Create:\r\nRuleName: -\r\nUtcTime: 2024-02-01 22:13:18.839\r\nProcessGuid: {23c79bc1-177e-65bc-6600-000000001200}\r\nProcessId: 4176\r\nImage: C:\\Windows\\System32\\conhost.exe\r\nFileVersion: 10.0.19041.3636 (WinBuild.160101.0800)\r\nDescription: Console Window Host\r\nProduct: Microsoft® Windows® Operating System\r\nCompany: Microsoft Corporation\r\nOriginalFileName: CONHOST.EXE\r\nCommandLine: \\??\\C:\\Windows\\system32\\conhost.exe 0xffffffff -ForceV1\r\nCurrentDirectory: C:\\Windows\r\nUser: NT AUTHORITY\\LOCAL SERVICE\r\nLogonGuid: {23c79bc1-176f-65bc-e503-000000000000}\r\nLogonId: 0x3E5\r\nTerminalSessionId: 0\r\nIntegrityLevel: System\r\nHashes: SHA256=C43CF46192DA061DD6169E55AAC4D2D08A6C33C039A7DAC0D88AA897661CBC87\r\nParentProcessGuid: {23c79bc1-177e-65bc-6500-000000001200}\r\nParentProcessId: 4164\r\nParentImage: C:\\Program Files (x86)\\Acunetix\\pg\\bin\\postgres.exe\r\nParentCommandLine: \"C:\\Program Files (x86)\\Acunetix\\pg\\bin\\postgres.exe\" -D \"C:\\ProgramData\\Acunetix\\db\" \r\nParentUser: NT AUTHORITY\\LOCAL SERVICE\"",
                                                  "data_win_eventdata_product":  "Microsoft® Windows® Operating System"
                                              }
                              },
                              {
                                  "_index":  "wazuh_alert_1_perfix_0",
                                  "_id":  "27ab9f01-c14f-11ee-b713-000c292285df",
                                  "_score":  1.0,
                                  "_source":  {
                                                  "source_reserved_ip":  "true",
                                                  "data_win_system_eventRecordID":  "3633",
                                                  "agent_id":  "002",
                                                  "agent_name":  "DESKTOP-GJA3NM0",
                                                  "data_win_system_severityValue":  "INFORMATION",
                                                  "gl2_remote_ip":  "192.168.59.130",
                                                  "data_win_system_eventID":  "1003",
                                                  "gl2_remote_port":  59624,
                                                  "source":  "192.168.59.130",
                                                  "gl2_source_input":  "65b67daf8ee8cf109aa47ccd",
                                                  "rule_level":  3,
                                                  "rule_firedtimes":  1,
                                                  "data_win_system_systemTime":  "2024-02-01T22:13:34.7153098Z",
                                                  "rule_mail":  "false",
                                                  "log_type":  "wazuh_1",
                                                  "data_win_system_task":  "1",
                                                  "decoder_name":  "windows_eventchannel",
                                                  "data_win_system_processID":  "0",
                                                  "data_win_system_threadID":  "0",
                                                  "data_win_system_channel":  "Application",
                                                  "rule_description":  "The Windows search service started.",
                                                  "gl2_source_node":  "90642c69-49a0-4566-8fcc-92a46421e216",
                                                  "id":  "1706825618.5784806",
                                                  "data_win_system_providerName":  "Microsoft-Windows-Search",
                                                  "data_win_system_version":  "0",
                                                  "data_win_system_providerGuid":  "{CA4E628D-8567-4896-AB6B-835B221F373F}",
                                                  "timestamp":  "2024-02-01 22:13:40.722",
                                                  "gl2_accounted_message_size":  2108,
                                                  "data_win_system_eventSourceName":  "Windows Search Service",
                                                  "data_win_system_opcode":  "0",
                                                  "gl2_processing_error":  "Replaced invalid timestamp value in message \u003c27ab9f01-c14f-11ee-b713-000c292285df\u003e with current time - Value \u003c2024-02-01T17:13:38.115-0500\u003e caused exception: Invalid format: \"2024-02-01T17:13:38.115-0500\" is malformed at \"T17:13:38.115-0500\".",
                                                  "streams":  [
                                                                  "65b800c7ef47be2bbc6927a3"
                                                              ],
                                                  "gl2_message_id":  "01HNKBR77JJ7YR1E8BZ99621BQ",
                                                  "data_win_system_computer":  "DESKTOP-GJA3NM0",
                                                  
                                                  "agent_ip_reserved_ip":  "true",
                                                  "rule_id":  "60668",
                                                  "agent_ip":  "192.168.59.131",
                                                  "manager_name":  "wazuhmanager",
                                                  "rule_groups2":  "windows_application",
                                                  "rule_groups1":  "windows",
                                                  "true":  1706825618.1198261,
                                                  "location":  "EventChannel",
                                                  "rule_groups":  "windows, windows_application",
                                                  "data_win_system_keywords":  "0x80000000000000",
                                                  "data_win_system_level":  "4",
                                                  "data_win_system_message":  "\"The Windows Search Service started.\n\""
                                              }
                              }
                          ]
             }
}



def test_irsoar_provide_new_alerts():
    # Prepare the config
    cfg = config_helper.Config().cfg
    integration_config = cfg["integrations"]["graylog"]

    alertArray = irsoar_provide_new_alerts(integration_config, TEST="OFFLINE")
    assert type(alertArray) == list, "irsoar_provide_new_alerts() should return a list of Alert objects"
    for alert in alertArray:
        assert type(alert) == Alert, "irsoar_provide_new_alerts() found an invalid Alert object in the list"


def test_create_alert_from_doc():
    mlog = logging_helper.Log("test_graylog")
    for num, doc in enumerate(TEST_RESULTS["hits"]["hits"]):
        alert = create_alert_from_doc(mlog, doc)
        assert type(alert) == Alert, "create_alert_from_doc() should return an Alert object"
        mlog.debug(alert)
    mlog.info("All tests passed")


# Test manually
test_irsoar_provide_new_alerts()
test_create_alert_from_doc()
